[features]
seeds = false
skip-lint = false
[programs.localnet]
gated_airdrop = "air4tyw7S12bvdRtgoLgyQXuBfoLrjBS7Fg4r91zLb1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
